export const Races = [
  { label: 'Anões', value: 'Anões' },
  { label: 'Elfos', value: 'Elfos' },
  { label: 'Goblins', value: 'Goblins' },
  { label: 'Halflings', value: 'Halflings' },
  { label: 'Humanos', value: 'Humanos' },
  { label: 'Meio-Gênios', value: 'Meio-Gênios' },
  { label: 'Minotauros', value: 'Minotauros' },
  { label: 'Lefou', value: 'Lefou' },
  { label: 'Gnomos', value: 'Gnomos' },
  { label: 'Meio-Elfos', value: 'Meio-Elfos' },
  { label: 'Meio-Orcs', value: 'Meio-Orcs' },
  { label: 'Centauros', value: 'Centauros' },
  { label: 'Elfos-do-Mar', value: 'Elfos-do-Mar' },
  { label: 'Gnolls', value: 'Gnolls' },
  { label: 'Nagahs', value: 'Nagahs' },
  { label: 'Sprites', value: 'Sprites' },
  { label: 'Trogs', value: 'Trogs' },
  { label: 'Hobgoblins', value: 'Hobgoblins' },
  { label: 'Herdeiros do Lobo', value: 'Herdeiros do Lobo' },
  { label: 'Aggelus', value: 'Aggelus' },
  { label: 'Bugbears', value: 'Bugbears' },
  { label: 'Centauros', value: 'Centauros' },
  { label: 'Elfos-do-Céu', value: 'Elfos-do-Céu' },
  { label: 'Elfos-do-Mar', value: 'Elfos-do-Mar' },
  { label: 'Gnolls', value: 'Gnolls' },
  { label: 'Gnomos', value: 'Gnomos' },
  { label: 'Herdeiros dos Animais', value: 'Herdeiros dos Animais' },
  { label: 'Hobgoblins', value: 'Hobgoblins' },
  { label: 'Medusa', value: 'Medusa' },
  { label: 'Meio-Dríades', value: 'Meio-Dríades' },
  { label: 'Meio-Elfos', value: 'Meio-Elfos' },
  { label: 'Meio-Orcs', value: 'Meio-Orcs' },
  { label: 'Minauros', value: 'Minauros' },
  { label: 'Nagahs', value: 'Nagahs' },
  { label: 'Orc', value: 'Orc' },
  { label: 'Povo Trovão: Caçadoras', value: 'Povo Trovão: Caçadoras' },
  { label: 'Povo Trovão: Ceratops', value: 'Povo Trovão: Ceratops' },
  { label: 'Povo Trovão: Pteros', value: 'Povo Trovão: Pteros' },
  { label: 'Povo Trovão: Velocis', value: 'Povo Trovão: Velocis' },
  { label: 'Sprites', value: 'Sprites' },
  { label: 'Sulfure', value: 'Sulfure' },
  { label: 'Trolls Nobres', value: 'Trolls Nobres' },
  { label: 'Trogs', value: 'Trogs' },
  { label: 'Sprites', value: 'Sprites' },
  { label: 'Meio Elfos-do-Mar', value: 'Meio Elfos-do-Mar' },
  { label: 'Feithnari', value: 'Feithnari' },
  { label: 'Hengeyokais', value: 'Hengeyokais' },
  { label: 'Kobolds', value: 'Kobolds' },
  { label: 'Minaques', value: 'Minaques' },
  { label: 'Nimbus', value: 'Nimbus' },
  { label: 'Sklirynei', value: 'Sklirynei' },
  { label: 'Moreau', value: 'Moreau' },
];
