export const classes = [
  { label: 'Abençoado', value: 'Abençoado', group: 'Divino' },
  { label: 'Artífice', value: 'Artífice', group: 'Especialista' },
  { label: 'Bárbaro', value: 'Bárbaro', group: 'Combatente' },
  { label: 'Bardo', value: 'Bardo', group: 'Especialista' },
  { label: 'Cavaleiro', value: 'Cavaleiro', group: 'Combatente' },
  { label: 'Clérigo', value: 'Clérigo', group: 'Divino' },
  { label: 'Druida', value: 'Druida', group: 'Divino' },
  { label: 'Feiticeiro', value: 'Feiticeiro', group: 'Arcano' },
  { label: 'Guerreiro', value: 'Guerreiro', group: 'Combatente' },
  { label: 'Ladino', value: 'Ladino', group: 'Especialista' },
  { label: 'Lutador', value: 'Lutador', group: 'Combatente' },
  { label: 'Mago', value: 'Mago', group: 'Arcano' },
  { label: 'Monge', value: 'Monge', group: 'Combatente' },
  { label: 'Ninja', value: 'Ninja', group: 'Especialista' },
  { label: 'Nobre', value: 'Nobre', group: 'Especialista' },
  { label: 'Paladino', value: 'Paladino', group: 'Divino' },
  { label: 'Ranger', value: 'Ranger', group: 'Especialista' },
  { label: 'Samaritano', value: 'Samaritano', group: 'Divino' },
  { label: 'Samurai', value: 'Samurai', group: 'Combatente' },
  { label: 'Swashbuckler', value: 'Swashbuckler', group: 'Especialista' },
];
