const LevelsModel = [
  {
    level: 1,
    experiencePoints: 0,
    expertises: [4, 1],
    talents: 1,
    BonusResistanceDamageCA: 0,
  },
  {
    level: 2,
    experiencePoints: 1000,
    expertises: [5, 1],
    talents: 0,
    BonusResistanceDamageCA: 1,
  },
  {
    level: 3,
    experiencePoints: 3000,
    expertises: [6, 1],
    talents: 2,
    BonusResistanceDamageCA: 1,
  },
  {
    level: 4,
    experiencePoints: 6000,
    expertises: [7, 1],
    talents: 0,
    BonusResistanceDamageCA: 2,
  },
  {
    level: 5,
    experiencePoints: 10000,
    expertises: [8, 1],
    talents: 3,
    BonusResistanceDamageCA: 2,
  },
  {
    level: 6,
    experiencePoints: 15000,
    expertises: [9, 1],
    talents: 0,
    BonusResistanceDamageCA: 3,
  },
  {
    level: 7,
    experiencePoints: 21000,
    expertises: [10, 1],
    talents: 4,
    BonusResistanceDamageCA: 3,
  },
  {
    level: 8,
    experiencePoints: 28000,
    expertises: [11, 1],
    talents: 0,
    BonusResistanceDamageCA: 4,
  },
  {
    level: 9,
    experiencePoints: 36000,
    expertises: [12, 1],
    talents: 5,
    BonusResistanceDamageCA: 4,
  },
  {
    level: 10,
    experiencePoints: 45000,
    expertises: [13, 1],
    talents: 0,
    BonusResistanceDamageCA: 5,
  },
  {
    level: 11,
    experiencePoints: 55000,
    expertises: [14, 1],
    talents: 6,
    BonusResistanceDamageCA: 5,
  },
  {
    level: 12,
    experiencePoints: 66000,
    expertises: [15, 1],
    talents: 0,
    BonusResistanceDamageCA: 6,
  },
  {
    level: 13,
    experiencePoints: 78000,
    expertises: [16, 1],
    talents: 7,
    BonusResistanceDamageCA: 6,
  },
  {
    level: 14,
    experiencePoints: 91000,
    expertises: [17, 1],
    talents: 0,
    BonusResistanceDamageCA: 7,
  },
  {
    level: 15,
    experiencePoints: 105000,
    expertises: [18, 1],
    talents: 8,
    BonusResistanceDamageCA: 7,
  },
  {
    level: 16,
    experiencePoints: 120000,
    expertises: [19, 1],
    talents: 0,
    BonusResistanceDamageCA: 8,
  },
  {
    level: 17,
    experiencePoints: 136000,
    expertises: [20, 1],
    talents: 9,
    BonusResistanceDamageCA: 8,
  },
  {
    level: 18,
    experiencePoints: 153000,
    expertises: [21, 1],
    talents: 0,
    BonusResistanceDamageCA: 9,
  },
  {
    level: 19,
    experiencePoints: 171000,
    expertises: [22, 1],
    talents: 10,
    BonusResistanceDamageCA: 9,
  },
  {
    level: 20,
    experiencePoints: 190000,
    expertises: [23, 1],
    talents: 0,
    BonusResistanceDamageCA: 10,
  },
];
export default LevelsModel;
